### ISSUE TITLE
Some RDF URLs cannot be retrieved

### ISSUE THREAD

**Issue by coret** [netwerk-digitaal-erfgoed/registry-api#31] opened 2021-01-21 17:28 UTC
Validating https://data.bibliotheken.nl/doc/dataset/rise-alba results in:
```
{
 "statusCode":500,
 "error":"Internal Server Error",
 "message":"Could not retrieve https://data.bibliotheken.nl/doc/dataset/rise-alba (500: unknown error)"
}
```
The dataset (KB/LODview) lacks creator and description and has mainEntityWebPage defined a Dataset, but a validation error would have resulted in a 400 error.

**Comment by ddeboer** [comment] 2021-01-21 17:45
```
Could not retrieve https://data.bibliotheken.nl/doc/dataset/rise-alba (500: unknown error)
    at ActorRdfDereferenceHttpParse.run (/Users/david/src/netwerk-digitaal-erfgoed/registry-api/node_modules/@comunica/actor-rdf-dereference-http-parse/lib/ActorRdfDereferenceHttpParseBase.js:56:27)
```

**Comment by coret** [comment] 2021-01-21 17:46
API now returns a HTTP 406 error

**Comment by coret** [comment] 2021-01-21 17:47
Could this be caused by the "schema:mainEntityWebPage a schema:Dataset"?

**Comment by ddeboer** [comment] 2021-01-22 10:26
No: SHACL will return a 400 rather than 406. Reported this issue at https://github.com/comunica/comunica/issues/775.

**Comment by ddeboer** [comment] 2021-01-25 07:31
@coret @EnnoMeijers As you’ll find [in the related Comunica issue](https://github.com/comunica/comunica/issues/775#issuecomment-765323473), this is due to misconfigured content negotiation on the server rather than an issue in Comunica.

Can one of you contact the person(s) responsible for the data.bibliotheken.nl infrastructure and report the issue to them?

**Comment by EnnoMeijers** [comment] 2021-01-25 07:39
I suggest @coret contacts René Voorburg about this problem.

**Comment by ddeboer** [comment] 2021-01-25 13:52
Closing this issue as other URLs seem to work fine.

**Comment by roland-c** [comment] 2021-01-25 13:52
This issue is caused by a missing configuration for mime types application/x-trig application/trig and application/n-quads on CN servers. Those mime types are added to config now. Only x-trig is really served as serialization. Others produce a 406.

**Closed by ddeboer** 2021-01-25 13:52 UTC
Labels: bug

**Comment by ddeboer** [comment] 2021-01-25 13:56
Hey @roland-c! Are these changes already applied?

This test case is still failing:

```
curl -H "Accept: application/n-quads,application/trig;q=0.95,application/ld+json;q=0.9,application/n-triples;q=0.8,text/turtle;q=0.6,application/rdf+xml;q=0.5,application/jso5,text/n3;q=0.35,application/xml;q=0.3,text/xml;q=0.3,image/svg+xml;q=0.3,text/html;q=0.2,application/xhtml+xml;q=0.18" https://data.bibliotheken.nl/doc/dataset/rise-alba -v
```

**Comment by roland-c** [comment] 2021-01-25 14:15
Hmm, not like this:
`curl -H "Accept: application/n-quads,application/trig;q=0.95,application/ld+json;q=0.9,application/n-triples;q=0.8,text/turtle;q=0.6,application/rdf+xml;q=0.5,application/jso5,text/n3;q=0.35,application/xml;q=0.3,text/xml;q=0.3,image/svg+xml;q=0.3,text/html;q=0.2,application/xhtml+xml;q=0.18" https://data.bibliotheken.nl/sparql?query=describe+%3Chttp%3A%2F%2Fdata.bibliotheken.nl%2Fid%2Fdataset%2Frise-alba%3E -v`

This goes directly to the SPARQL enpoint evading the resolver. 
The issue is within the resolver. I'll look further into it.
